blank_issues_enabled: false
contact_links:
  - name: Вопросы и помощь
    url: https://github.com/mazhievadlan7/Office3D/discussions
    about: Пожалуйста, задавайте вопросы в Discussions, а не открывайте issue.
